---
- name: Ops Restore Kafka Pre
  hosts: kafka_broker
  gather_facts: no
  tasks:
    - name: duply pre restore
      shell: duply kafka_restore pre

- name: Ops Restore kafka
  hosts: kafka_broker
  gather_facts: no
  tasks:
    - name: duply restore
      shell: duply kafka restore

- name: Ops Restore kafka Post
  hosts: kafka_broker
  gather_facts: no
  tasks:
    - name: duply post restore
      shell: duply kafka_restore post