---
- name: Ops Restore Zookeeper Pre
  hosts: zookeeper
  gather_facts: no
  tasks:
    - name: duply pre restore
      shell: duply zookeeper_restore pre

- name: Ops Restore Zookeeper
  hosts: zookeeper
  gather_facts: no
  tasks:
    - name: duply restore
      shell: duply zookeeper restore

- name: Ops Restore Zookeeper Post
  hosts: zookeeper
  gather_facts: no
  tasks:
    - name: duply post restore
      shell: duply zookeeper_restore post